export const SET_POSTS = 'SET_POSTS';
export const FETCH_POSTS = 'FETCH_POSTS';
export const ADD_TAG_FILTER = 'ADD_TAG_FILTER';
export const REMOVE_TAG_FILTER = 'REMOVE_TAG_FILTER';
export const API = 'API';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
