export const NETWORK_FAILURE = 'NETWORK_FAILURE';

export const SET_POSTS = 'SET_POSTS';
export const SET_PRIVATE_POSTS = 'SET_PRIVATE_POSTS';

export const FETCH_POSTS = 'FETCH_POSTS';
export const ADD_TAG_FILTER = 'ADD_TAG_FILTER';
export const REMOVE_TAG_FILTER = 'REMOVE_TAG_FILTER';
export const API = 'API';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const USER_LOGOUT = 'USER_LOGOUT';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';

export const PUBLISH_POST = 'PUBLISH_POST';
export const UNPUBLISH_POST = 'UNPUBLISH_POST';
